### PR TITLE
Updated

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
updated

### CODE REVIEW

**Comment by Bharadwajshivam28** [comment]
@Jaysmito101 sir i have done with above 300 lines

**Comment by Bharadwajshivam28** [comment]
@Jaysmito101 as you said you will merge than i will move forward

**Comment by Bharadwajshivam28** [comment]
so review and merge it sir so i move forward @Jaysmito101

**Comment by Jaysmito101** [comment]
@Bharadwajshivam28 It is very clear that all the changes you proposed here are completely made using something ChatGPT ( GPT3 ). As far as i see you did not even go through the thing yourself as its quite nonsensical at places. This type of contributions are not allowed.

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 It is very clear that all the changes you proposed here are completely made using something ChatGPT ( GPT3 ). As far as i see you did not even go through the thing yourself as its quite nonsensical at places. This type of contributions are not allowed.

Ok sir I will update it without using other sources

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 It is very clear that all the changes you proposed here are completely made using something ChatGPT ( GPT3 ). As far as i see you did not even go through the thing yourself as its quite nonsensical at places. This type of contributions are not allowed.

Sir just say that how much line at first I should update for merge the I will move forward like how much line first I pr then I move forward

**Comment by Jaysmito101** [comment]
@Bharadwajshivam28 As i said you can do about 100-200 lines at one go.

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 As i said you can do about 100-200 lines at one go.

Sir first of all is 100 lines good to go first?

**Pull request closed without merging**
