### PR TITLE
Updated

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
Review the updated.c file

### CODE REVIEW

**Comment by Jaysmito101** [comment]
Why create a seperate file?

**Comment by Bharadwajshivam28** [comment]
sir i will make into one but please review it is it coreect till no @Jaysmito101

**Comment by Jaysmito101** [comment]
@Bharadwajshivam28 it's not possible to check for updates you have made in a 13k lines file. Please update CGL.h so that it's possible to check.

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 it's not possible to check for updates you have made in a 13k lines file. Please update CGL.h so that it's possible to check.

Ok sir

**Comment by Bharadwajshivam28** [comment]
Screenshot from 2023-02-10 20-37-54
Screenshot from 2023-02-10 20-38-21

**Pull request closed without merging**
