### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Code1705**
#36  issue solved , now please could you merge my PR?

### CODE REVIEW

**Comment by Jaysmito101** [comment]
@Code1705 where is the proper documentation? Also what's the purpose of adding these stickers/badges on the readme? Also why do you need to include contributors in the readme itself? GitHub shows a proper list of contributors just beside the readme

**Comment by Code1705** [comment]
I made the readme for other projects in this way only and stickers badges are required for presentable project to have an attractive look, .Definately beside readme  contributors are mentioned  it is given  but as I  have seen for other projects too it is given within readme.

**Comment by Jaysmito101** [comment]
@Code1705 I am not asking for what other projects are doing. What I am asking is what is the purpose of these? I mean if we are adding something in the readme its for a purpose right? The stickers you added serve no purpose at all do they? The reason I assigned you this issue is because you mentioned you were going to create *proper documentation* . As far as other projects, I do not think many real world large scale projects use any of these things.

**Comment by Jaysmito101** [comment]
@Code1705 hey, this has been inactive for some time. Are you still interested in working on it?

**Comment by Jaysmito101** [comment]
@Code1705 I am closing this due to inactivity

**Pull request closed without merging**
