### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by utkarsh006**
- PR Raised for Issue #13
- SEE THE CHANGES [HERE](https://github.com/utkarsh006/cgl/blob/Readme_Update/README.md)
- Enhanced README file for this Repo for better readability of users.
- Added Contributors section and about the details of the repo.
- Formatted some lines of text.

### CODE REVIEW

**Review by Jaysmito101 — CHANGES_REQUESTED** [review]
Here are some things you should change:

* Maintained batch is present twice
* There is no need for a language badge as well is clear that it's a c library
* Don't mention something like "Star this repo" as you know if people find this useful they will star it anyway
* Target platforms should be a list not a single line which will be difficult to read at a look.
* Also the features of CGL shouldn't be put inside a detail tag as that's the main content and there is no point in hiding it.

Thanks

**Review by Jaysmito101 — CHANGES_REQUESTED** [review]
I reviewed the changes. 
Some thoughts:
Just try opening the readme in a mobile device you will see that the target platforms are not visible. Just make a simple list.

Also it's better to have the features in the main page as that's the most important thing people are looking for in the readme.

And avoid using detail tag as people might just miss the entire section when taking a quick look

**Comment by utkarsh006** [comment]
@Jaysmito101 Review Now.

**Comment by Jaysmito101** [comment]
Thanks for your contribution!🙂

**Pull request merged**
